# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Raise Your Hand If You're New To This
email: mrowlan1@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An R blog for the rest of us.
baseurl: "/Blog" # the subpath of your site, e.g. /blog
url: "https://myfanwy.github.io" # the base hostname & protocol for your site
twitter_username: voovarb
github_username:  Myfanwy

# Build settings
markdown: kramdown
